create_aws_credentials_file: no

stack_outputs: {}
stack_name: kameshs-gloo-demos

aws_create_vpc: yes
aws_delete_vpc: no
eks_create: yes
eks_delete: no

eks_cluster_name: kameshs-gloo-demos
eks_nodegroup_name: kameshs-node-m5xlarge
eks_nodegroup_desired_capacity: 1
eks_cluster_node_instance_type: m5.xlarge
eks_node_volume_size_gb: 80
aws_vpc_cidr: 172.25.0.0/16
aws_region: ap-south-1
eks_kubernetes_version: "1.21"

eks_private_subnet_cidr_blocks:
 a: 172.25.1.0/24 
 b: 172.25.2.0/24
 c: 172.25.3.0/24

eks_public_subnet_cidr_blocks:
 a: 172.25.5.0/24 
 b: 172.25.6.0/24
 c:  172.25.7.0/24

node_ready_query: "resources[*].status.conditions[?reason=='KubeletReady'].status"
