- name: "Delete Kubernetes Cluster"
  google.cloud.gcp_container_cluster:
    name: "{{ gke_cluster_name }}"
    description: "Kameshs Gloo Demos Cluster"
    network: "{{ gcp_vpc_name }}"
    subnetwork: "{{ gcp_vpc_name }}-k8s-subnet"
    initial_node_count: 1
    ip_allocation_policy:
      create_subnetwork: no
      # pod secondary ip range
      cluster_secondary_range_name: "{{ gcp_vpc_name }}-pods-range"
      # services secondary ip range
      services_secondary_range_name: "{{ gcp_vpc_name }}-services-range"
      use_ip_aliases: yes
    # TODO Get this dynamically by query 
    location: "{{ gke_cluster_location }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent
  register: k8s_cluster

- name: "Delete Kubernetes Cluster Node Pool"
  google.cloud.gcp_container_node_pool:
    name: "{{ gke_cluster_name }}-node-pool"
    initial_node_count: "{{ gke_cluster_node_size }}"
    cluster: "{{ k8s_cluster }}"
    config:
     disk_size_gb: "{{ gke_cluster_node_disk_size }}"
     machine_type: "{{ gke_cluster_node_type }}"
     tags:
      - gloo
    location: "{{ gke_cluster_location }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: absent

- name: "Remove KubeConfig"
  ansible.builtin.file:
    dest: "{{ work_dir }}/.kube/gke_{{ gke_cluster_name }}.kubeconfig"
    state: absent