
gcp_cred_kind: serviceaccount
create_gcp_credentials_file: no
gcp_cred_file: "{{ lookup('env','GOOGLE_APPLICATION_CREDENTIALS') }}"

# VPC
gcp_create_vpc: yes
gcp_delete_vpc: no
gcp_vpc_name: kameshs-k8s-vpc

# k8s
gke_create: yes
gke_delete: no
gke_cluster_name: kameshs-gloo-demos
gke_node_count: 3
gke_kubernetes_version: 1.21.4-gke.301
gke_release_channel: RAPID
gke_cluster_json_query: "resources[?name == '{{ gke_cluster_name }}']"

# VPN
gcp_create_vpn: yes
gke_cluster_node_type: n1-standard-4
gke_cluster_node_disk_size: 80
gke_cluster_location: asia-south1-c
gke_cluster_node_size: 3

# Subnets
k8s_subnet_cidr: 172.16.0.0/28
k8s_pods_ip_range: 172.17.0.0/16
k8s_services_ip_range: 172.18.0.0/20
