################################################################
# START VPC 
################################################################
- name: "GCP::Create VPC"
  google.cloud.gcp_compute_network:
    name: "{{ gcp_vpc_name }}"
    auto_create_subnetworks: no
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: present
  register: k8s_vpc_network
################################################################
# END VPC 
################################################################

################################################################
# START KUBERNETES VPC SUBNETS
################################################################
- name: "Create VPC Subnetwork {{ k8s_subnet_cidr }}"
  google.cloud.gcp_compute_subnetwork:
    name: "{{ gcp_vpc_name }}-k8s-subnet"
    network: "{{ k8s_vpc_network }}"
    ip_cidr_range: "{{ k8s_subnet_cidr }}"
    secondary_ip_ranges:
     - range_name: "{{ gcp_vpc_name }}-pods-range"
       ip_cidr_range: "{{ k8s_pods_ip_range }}"
     - range_name: "{{ gcp_vpc_name }}-services-range"
       ip_cidr_range: "{{ k8s_services_ip_range }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    region: "{{ gcp_region }}"
    state: present
  register: network_k8s_subnet

################################################################
# END START KUBERNETES VPC SUBNETS
################################################################