civo_create: yes
civo_delete: no

create_civo_credentials_file: no
civo_cli_version: v0.7.32
civo_api_url: 'https://api.civo.com/v2'
civo_network_label: 'Default'
civo_k3s_cluster_name: kameshs-gloo-demos
civo_k3s_cluster_size: g3.k3s.xlarge
civo_k3s_cluster_nodes: 1
# LON1, FRA1, NYC1 
civo_region: LON1
civo_kubernetes_version: 1.21.2+k3s1
civo_firewall_rules: 80,443,6443,8080,8443,9900,15443,15021,15012,15017
civo_clusters_list_query: "items[?name=='{{ civo_k3s_cluster_name }}']"
civo_network_query: "json[?label=='{{ civo_network_label }}']"