apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: ecommerce-portal
spec:
  displayName: E-commerce Portal
  description: The Gloo Portal for the Petstore API and much more!
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  favicon:
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  customStyling: {}
  staticPages: []

  domains:
  - portal.kameshs.me

  publishedEnvironments:
  - name: dev
    namespace: default

  allApisPublicViewable: true # this will make APIs visible by unauthenticated users

  # ------------------- Authentication  ---------------------
  oidcAuth:
    clientId: gloo-demos-client
    clientSecret:
      name: petstore-portal-oidc-secret
      namespace: default
      key: client_secret
    groupClaimKey: group
    issuer: http://35.200.196.74:8080/auth/realms/master
  portalUrlPrefix: http://portal.kameshs.me/
  # ---------------------------------------------
