apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: ecommerce-portal
spec:
  displayName: E-commerce Portal
  description: The Gloo Portal for the Petstore API and much more!
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  favicon:
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  customStyling: {}
  staticPages: []

  domains:
  - portal.kameshs.me

  publishedEnvironments:
  - name: dev
    namespace: default

  allApisPublicViewable: true # this will make APIs visible by unauthenticated users

  # ------------------- Authentication  ---------------------
  oidcAuth:
    clientId: 0oa27ibhgf4QiAikO5d7
    clientSecret:
      name: petstore-portal-oidc-secret
      namespace: default
      key: client_secret
    groupClaimKey: groups
    additionalScopes:
     - groups
    issuer: https://dev-25432879.okta.com
  portalUrlPrefix: http://portal.kameshs.me/
  # ---------------------------------------------
