---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS Cluster definition.'

Parameters:

  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: List of Security Group Ids to attach to cluster nodes

  SubnetIds:
    Type: CommaDelimitedList
    Description: List of public and private subnets to be used with the cluster networking.

  ClusterName:
    Type: String
    Description: EKS Kubernetes cluster name.

  KubernetesVersion:
    Type: String
    Default: "1.20"
    Description: EKS Kubernetes cluster version.

Resources:
  EKSIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Principal:
            Service:
              - eks.amazonaws.com
          Action: sts:AssumeRole
      RoleName: !Sub '${ClusterName}-eks-role'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  
  Cluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: !Ref ClusterName
      Version: !Ref KubernetesVersion
      RoleArn: !GetAtt EKSIAMRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref SubnetIds
    DependsOn: EKSIAMRole

Outputs:

  ClusterName:
    Value: !Ref ClusterName
    Description: Cluster Name
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ClusterName"

  ClusterEndpoint:
    Value: !GetAtt Cluster.Endpoint
    Description: Cluster Endpoint
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-ClusterEndpoint"

  CertificateAuthorityData:
    Value: !GetAtt Cluster.CertificateAuthorityData
    Description: Cluster CertificateAuthorityData